version: 0.0
os: linux
files:
  - source: ./docker-compose.production.yml
    destination: /home/ubuntu/e1-grupo3-backend/
  - source: scripts
    destination: /home/ubuntu/e1-grupo3-backend/scripts

hooks:
  ApplicationStop:
    - location: ./scripts/application-stop.sh
      timeout: 10000
  AfterInstall:
    - location: ./scripts/after-install.sh
      timeout: 3000
  ApplicationStart:
    - location: ./scripts/application-start.sh
      timeout: 3000
  ValidateService:
    - location: ./scripts/validate-service.sh
      timeout: 3000
