name: Frontend CI Pipeline

on:
  push:
    branches:
      - entrega2
      - entrega3
  pull_request:
    branches:
      - entrega2
      - entrega3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install ESLint dependencies
      run: npm install eslint

    - name: Run ESLint
      run: npm run lint